// Every user-facing string lives here. Hinglish, punchy, zero corporate.

export const copy = {
  appName: 'GALTI',
  tagline: 'Solve mat karo. Pakdo.',

  home: {
    playerFallback: 'Player',
    playerTitle: 'Red Pen Rookie',
    dayStreak: 'Day Streak',
    totalScore: 'Total Score',
    streakTitle: 'STREAK',
    streakSub: '45 sec. Endless Hunt',
    dailyTitle: 'DAILY GALTI',
    dailySub: 'Ek problem, ek mauka',
    duelTitle: 'CHALLENGE A FRIEND',
    duelSub: '5-round async duel',
    liveTitle: 'LIVE DUEL',
    liveSub: 'Real-time 1v1',
    soon: 'SOON',
    tabs: { home: 'Home', stats: 'Stats', leaderboard: 'Leaderboard', profile: 'Profile' },
  },

  offline: 'Net chala gaya. Wapas aao, galtiyan wahi milengi.',

  onboarding: {
    title: 'Kaun ho aap? 🖊️',
    sub: 'Bas naam aur ek chehra. No signup, no password.',
    namePlaceholder: 'Aapka naam',
    go: 'Chalo shuru karein',
    error: 'Kuch gadbad hui. Phir try karo.',
  },

  daily: {
    headerLabel: (n) => `DAILY #${n}`,
    seeResult: 'Result dekho',
    wonTitle: 'AAJ KA PAKDA! 🎉',
    halfTitle: 'ADHA SAHI! ✏️',
    lostTitle: 'AAJ NIKAL GAYA 😶',
    galtiNumber: (n) => `Daily Galti #${n}`,
    catchLabel: 'Galti pakdi',
    diagLabel: 'Wajah sahi',
    timeLabel: 'Time',
    scoreLabel: 'Score',
    firstFew: 'Be one of the first! 🌅',
    pctLine: (pct) => `${pct}% players ne aaj pakdi`,
    copyBtn: 'Copy result 📋',
    copied: 'Copy ho gaya! ✓',
    cardNotPlayed: 'Ek problem, ek mauka',
    cardPlayed: (p) =>
      `Aaj: ${p.caught ? '🟢' : '🔴'}${p.diagnosed ? '🟢' : '🔴'} · +${p.score}`,
  },

  duel: {
    headerLabel: (n) => `DUEL · ROUND ${n}`,
    createTitle: 'Challenge a Friend',
    createSub: '5 rounds khelo, phir link bhejo. Dost wahi 5 khelega.',
    createGo: '5 rounds shuru karo 🖊️',
    shareTitle: 'Duel taiyar! 🔥',
    shareSub: 'Yeh link bhejo. Dost ko login ki zaroorat nahi.',
    codeLabel: 'Duel Code',
    expiresNote: '24 ghante mein expire',
    waBtn: 'WhatsApp pe bhejo',
    waText: (link) => `Maine 5 galtiyan pakdi. Tu pakad ke dikha 🖊️ ${link}`,
    copyLink: 'Copy Link',
    copiedLink: 'Link copy ho gaya ✓',
    waitingTitle: 'Intezaar... ⏳',
    waitingSub: 'Dost ne abhi khela nahi. Link dubara bhej do?',
    acceptTitle: (name) => `${name} ne challenge bheja hai`,
    acceptSub: '5 rounds · Same problems · No login',
    acceptGo: 'Accept Challenge 🖊️',
    playingAs: (name) => `Playing as ${name}`,
    errorTitle: 'Yeh duel nahi mila 😶',
    errorSub: 'Link galat hai ya expire ho gaya. Naya duel banao?',
    resultWon: 'YOU WON! 🎉',
    resultLost: 'HAAR GAYE 😤',
    resultTie: 'BARABAR! 🤝',
    resultSpectator: 'RESULT',
    roundSummary: 'Round Summary',
    thRound: 'Round',
    thCatch: 'Catch',
    thDiag: 'Diag.',
    you: 'You',
    rematch: 'Rematch',
    newDuel: 'New Duel',
    finishToShare: 'Result dekho',
    nextRound: 'Next Round',
  },

  live: {
    title: 'Live Duel',
    sub: 'Real-time 1v1. Pehle pakde, woh jeete.',
    createBtn: 'Room banao ⚡',
    joinPlaceholder: 'CODE',
    joinBtn: 'Room join karo',
    lobbyTitle: 'Room taiyar!',
    lobbySub: 'Dost ko code batao. Dono ready → shuru.',
    waitingOpponent: 'Opponent ka intezaar…',
    readyBtn: 'Ready! 🖊️',
    readyWait: 'Dost ready nahi abhi…',
    youReady: 'Aap ready ho ✓',
    roundLabel: (n, t) => `LIVE · ROUND ${n}/${t}`,
    lockedYou: 'PAKDA! Ab wajah batao 🔴',
    lockedThem: (name) => `${name} ne pehle pakad liya 😤`,
    failedYou: 'Galat step! Is round se bahar ❌',
    nobody: 'Kisi ne nahi pakdi 😶',
    theirTurnDiag: (name) => `${name} wajah soch raha hai…`,
    roundWonYou: 'ROUND AAPKA! 🎉',
    roundWonThem: (name) => `Round ${name} ka 😐`,
    finalWon: 'YOU WON! 🎉',
    finalLost: 'HAAR GAYE 😤',
    finalTie: 'BARABAR! 🤝',
    forfeitNote: 'Opponent bhaag gaya. Walkover! 🏆',
    disconnected: (s) => `Opponent ka net gaya… ${s}s mein walkover`,
    errNotFound: 'Room nahi mila. Code check karo?',
    errFull: 'Room full hai ya game shuru ho chuka.',
    playAgain: 'Ek aur duel ⚡',
  },

  round: {
    hint: 'Galat step pe tap karo 🔴',
    roundLabel: (n) => `ROUND ${n}`,
    lives: 'LIVES',
    sec: 'SEC',
    solvePrefix: 'Solve:',
    diagnosisTitle: 'Kyun galat hai?',
    diagnosisSub: (n) => `Step ${n} galat hai. Kyun?`,
  },

  verdict: {
    fullStamp: 'PAKDA! 🎉',
    fullSub: 'Step bhi sahi, wajah bhi sahi. Teacher ban gaye aap 🖊️',
    partialStamp: 'ADHA SAHI! 🎉',
    partialSub: 'Step sahi pakda, par wajah galat.',
    missStamp: 'GALAT STEP ❌',
    missSub: 'Aankh se nikal gaya… asli galti yahan thi:',
    timeoutStamp: 'TIME KHATAM ⏱',
    timeoutSub: 'Ghadi jeet gayi. Galti yeh thi:',
    points: (n) => `+${n} points`,
    sahiStep: 'Sahi Step',
    stepN: (n) => `Step ${n}`,
    sahiJawab: 'Sahi Jawab',
    breakdownTitle: 'Score Breakdown',
    next: 'Next Round',
    seeResult: 'Result dekho',
    breakdown: {
      catch: 'Step pakda sahi',
      diagnosis: 'Wajah sahi',
      speed: (s) => `Time bonus (${s}s)`,
      multiplier: (m) => `Streak (${m}x)`,
      partialFlat: 'Adha credit',
      total: 'Total',
    },
  },

  runOver: {
    title: 'Kalam neeche 🖊️',
    score: 'Score',
    bestStreak: 'Best streak',
    accuracy: 'Accuracy',
    rounds: 'Rounds',
    again: 'Ek aur run 🔴',
    home: 'Ghar wapas',
  },

  // Hinglish label + formal name for each error type (taxonomy of 8, §4)
  diagnosisLabels: {
    'sign-error': { label: 'Sign error', sub: 'Sign galat ho gaya', icon: '➕' },
    'wrong-formula': { label: 'Formula hi galat', sub: 'Wrong formula used', icon: '📐' },
    'calc-slip': { label: 'Calculation slip', sub: 'Arithmetic mistake', icon: '🧮' },
    'invalid-operation': { label: 'Invalid operation', sub: 'Not allowed in maths', icon: '🚫' },
    'dropped-term': { label: 'Term gir gaya', sub: 'Dropped term', icon: '🍂' },
    'wrong-substitution': { label: 'Galat substitution', sub: 'Wrong value plugged in', icon: '🔁' },
    'unit-error': { label: 'Unit ka lafda', sub: 'Unit error', icon: '📏' },
    'misread-question': { label: 'Sawaal galat padha', sub: 'Misread question', icon: '👓' },
  },
};
