services:
  - type: web
    name: galti
    runtime: node
    buildCommand: npm install --production=false && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
